//! Golden-parity tests against the Go-parser fixtures (dataflash formats).
//!
//! The fixture trees under `tests/fixtures/<name>/` were generated by
//! `cmd/fixturegen` (Go). The harness re-parses the input bytes through the
//! Rust streaming session — in tiny chunks, to exercise the incremental
//! scanners — and asserts equivalence against the shared battery in
//! tests/golden_common/mod.rs (byte-exact TypeBody/curve blobs plus
//! value-level summary/parameters/series/typeSchema).

mod golden_common;

use golden_common::{fixtures, run_golden};

#[test]
fn golden_apm_text() {
    let dir = fixtures().join("apm_text");
    let input = dir.join("apm_text.log");
    run_golden(&dir, &input);
}

#[test]
fn golden_apm_bin() {
    let dir = fixtures().join("apm_bin");
    let input = dir.join("apm_bin.bin");
    run_golden(&dir, &input);
}
