//! Data-driven MAVLink dialect table: the compile-time replacement for Go's
//! reflection-based `buildMessageLayout`. The table is generated by
//! `go run ./cmd/fixturegen` from the same gomavlib ardupilotmega dialect the
//! Go parser uses (see cmd/fixturegen/mavlink_dump.go for the kind rules).
//!
//! Column offsets in the produced FormatDef are TRUE WIRE offsets following
//! MAVLink field reordering (non-extension fields sorted by decreasing wire
//! width, stable; extensions keep declaration order at the end — gomavlib
//! pkg/message/readwriter.go). gomavlib enums (uint64 kinds), strings, and
//! byte arrays carry no column (Go's glTypeFor drops them) but DO occupy wire
//! bytes, so they are "skip" entries carrying only their width. Column order
//! stays struct declaration order (Go's layout builder); the accumulator packs
//! a dense body from the numeric columns only — byte-identical to Go's
//! packers-into-scratch-buffer approach.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::format::{FieldGlType, FieldLayout, FormatDef};

use super::scale::{unit_scale_for, FieldKind};

/// FMT-style source type name for a wire kind (Go tlog layout.go
/// `origTypeName`; float32 renders as "float").
fn orig_type_name(kind: FieldKind) -> &'static str {
    match kind {
        FieldKind::U8 => "uint8",
        FieldKind::I8 => "int8",
        FieldKind::U16 => "uint16",
        FieldKind::I16 => "int16",
        FieldKind::U32 => "uint32",
        FieldKind::I32 => "int32",
        FieldKind::F32 => "float",
        FieldKind::Char => "char",
    }
}

/// One wire field of a dialect message.
#[derive(Debug, Clone)]
pub enum DialectField {
    /// A body column with its wire kind and wire offset.
    Column {
        name: String,
        kind: FieldKind,
        off: usize,
    },
    /// Wire bytes without a column (enums, strings, byte arrays, 64-bit ints).
    Skip { name: String, width: usize },
}

/// One dialect message: struct name (for FMT-name conversion) + fields in
/// declaration order.
#[derive(Debug, Clone)]
pub struct DialectMessage {
    pub struct_name: String,
    pub fields: Vec<DialectField>,
}

fn table() -> &'static HashMap<u32, DialectMessage> {
    static TABLE: OnceLock<HashMap<u32, DialectMessage>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let raw: serde_json::Value =
            serde_json::from_str(include_str!("../../data/mavlink-dialect.json"))
                .expect("embedded dialect table is valid JSON");
        let mut out = HashMap::new();
        let Some(msgs) = raw["messages"].as_object() else {
            return out;
        };
        for (id, m) in msgs {
            let Ok(id) = id.parse::<u32>() else { continue };
            let struct_name = m["structName"].as_str().unwrap_or_default().to_string();
            let mut fields = Vec::new();
            if let Some(list) = m["fields"].as_array() {
                for f in list {
                    let Some(name) = f["name"].as_str() else {
                        continue;
                    };
                    let kind = f["kind"].as_str().unwrap_or_default();
                    let off = f["off"].as_u64().unwrap_or(0) as usize;
                    if kind == "skip" {
                        fields.push(DialectField::Skip {
                            name: name.to_string(),
                            width: f["w"].as_u64().unwrap_or(0) as usize,
                        });
                    } else if let Some(k) = FieldKind::parse(kind) {
                        fields.push(DialectField::Column {
                            name: name.to_string(),
                            kind: k,
                            off,
                        });
                    }
                }
            }
            out.insert(
                id,
                DialectMessage {
                    struct_name,
                    fields,
                },
            );
        }
        out
    })
}

/// Converts a Go struct name (e.g. "MessageAttitude") into the MAVLink FMT
/// name (e.g. "ATTITUDE"), inserting underscores at lower/digit-to-upper-case
/// boundaries and uppercasing every letter.
pub fn format_name_from_message(type_name: &str) -> String {
    let s = type_name.strip_prefix("Message").unwrap_or(type_name);
    let mut out = String::with_capacity(s.len() + 4);
    let b = s.as_bytes();
    for (i, &c) in b.iter().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            let prev = b[i - 1];
            if prev.is_ascii_lowercase() || prev.is_ascii_digit() {
                out.push('_');
            }
        }
        out.push(c.to_ascii_uppercase() as char);
    }
    out
}

/// The FMT name for a message id (via its struct name).
pub fn format_name(msg_id: u32) -> Option<String> {
    table()
        .get(&msg_id)
        .map(|m| format_name_from_message(&m.struct_name))
}

/// Full wire length of a message payload (skip widths included).
pub fn wire_len(msg_id: u32) -> Option<usize> {
    table().get(&msg_id).map(|m| {
        m.fields
            .iter()
            .map(|f| match f {
                DialectField::Column { kind, .. } => kind.size(),
                DialectField::Skip { width, .. } => *width,
            })
            .sum()
    })
}

/// Builds the FormatDef for a message id. Column offsets are the reordered
/// wire offsets from the generated table; skips carry no column.
pub fn format_def(msg_id: u32) -> Option<FormatDef> {
    let m = table().get(&msg_id)?;
    let mut def = FormatDef {
        name: format_name_from_message(&m.struct_name),
        ..Default::default()
    };
    for f in &m.fields {
        let DialectField::Column { name, kind, off } = f else {
            continue;
        };
        let gl = match kind {
            FieldKind::U8 => FieldGlType::Uint8,
            FieldKind::I8 => FieldGlType::Int8,
            FieldKind::U16 => FieldGlType::Uint16,
            FieldKind::I16 => FieldGlType::Int16,
            FieldKind::U32 => FieldGlType::Uint32,
            FieldKind::I32 => FieldGlType::Int32,
            FieldKind::F32 => FieldGlType::Float32,
            FieldKind::Char => unreachable!("char is a skip, not a column"),
        };
        def.field_names.push(name.clone());
        def.layout.push(FieldLayout {
            name: name.clone(),
            gl_type: gl,
            size: kind.size(),
            scale: unit_scale_for(name, *kind),
            offset: *off,
            in_body: true,
            orig_type: orig_type_name(*kind).to_string(),
        });
    }
    Some(def)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_convert() {
        assert_eq!(format_name_from_message("MessageAttitude"), "ATTITUDE");
        assert_eq!(
            format_name_from_message("MessageGlobalPositionInt"),
            "GLOBAL_POSITION_INT"
        );
        assert_eq!(format_name_from_message("MessageRcChannels"), "RC_CHANNELS");
    }

    #[test]
    fn table_has_core_messages() {
        assert_eq!(format_name(30).as_deref(), Some("ATTITUDE"));
        assert_eq!(format_name(0).as_deref(), Some("HEARTBEAT"));

        let fd = format_def(30).unwrap();
        let names: Vec<&str> = fd.field_names.iter().map(|s| s.as_str()).collect();
        assert_eq!(
            names,
            vec![
                "TimeBootMs",
                "Roll",
                "Pitch",
                "Yaw",
                "Rollspeed",
                "Pitchspeed",
                "Yawspeed"
            ]
        );
        // Roll is radians on the wire → degrees for display.
        assert_eq!(fd.layout[1].scale, 180.0 / std::f64::consts::PI);
    }

    #[test]
    fn wire_offsets_follow_field_reordering() {
        // HEARTBEAT wire: CustomMode (uint32) sorts first at 0; the 1-byte
        // fields keep declaration order behind it (Type@4, Autopilot@5,
        // BaseMode@6, SystemStatus@7), MavlinkVersion at 8.
        let fd = format_def(0).unwrap();
        assert_eq!(fd.field_names, vec!["CustomMode", "MavlinkVersion"]);
        assert_eq!(fd.layout[0].offset, 0);
        assert_eq!(fd.layout[1].offset, 8);
        assert_eq!(wire_len(0), Some(9));

        // PARAM_VALUE wire: ParamValue (float) sorts first at 0, then the
        // uint16 pair (ParamCount@4, ParamIndex@6), then the 1-byte class in
        // declaration order: ParamId string occupies 8..24, ParamType at 24.
        let fd = format_def(22).unwrap();
        let idx = fd
            .field_names
            .iter()
            .position(|n| n == "ParamValue")
            .unwrap();
        assert_eq!(fd.layout[idx].offset, 0);
        assert_eq!(wire_len(22), Some(25));

        // GPS_RAW_INT wire: TimeUsec (uint64) at 0, then the 4-byte class
        // (Lat@8, Lon@12, Alt@16), 2-byte class, 1-byte class last.
        let fd = format_def(24).unwrap();
        assert_eq!(fd.layout[0].name, "Lat");
        assert_eq!(fd.layout[0].offset, 8);
        assert_eq!(fd.layout[0].scale, 1e-7);

        // BATTERY_STATUS wire: the int32 pair leads (CurrentConsumed@0,
        // EnergyConsumed@4), Temperature@8, Voltages@10..30, CurrentBattery@30,
        // then the 1-byte class (Id@32, BatteryFunction@33, Type@34,
        // BatteryRemaining@35), extensions after — the case that exposed the
        // reordering ( Voltages sits 5 bytes later than declaration order).
        let fd = format_def(147).unwrap();
        let v0 = fd
            .field_names
            .iter()
            .position(|n| n == "Voltages[0]")
            .unwrap();
        assert_eq!(fd.layout[v0].offset, 10);
        let cb = fd
            .field_names
            .iter()
            .position(|n| n == "CurrentBattery")
            .unwrap();
        assert_eq!(fd.layout[cb].offset, 30);
        assert_eq!(wire_len(147), Some(54));
    }
}
